# Generated by Django 2.2.10 on 2021-08-16 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='наименование опроса')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('start_date', models.DateTimeField(verbose_name='дата старта')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250, verbose_name='текст вопроса')),
                ('answer_type', models.CharField(choices=[('TEXT', 'текстом'), ('ONEVARIANT', 'с выбором одного варианта'), ('MULTIVARIANT', 'с выбором нескольких вариантов')], default='TEXT', max_length=12, verbose_name='тип ответа')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QuestionSet')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewee_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='код пользователя')),
                ('start_date', models.DateTimeField(verbose_name='дата опроса')),
                ('loggedin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QuestionSet')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=50, verbose_name='текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=50, verbose_name='текст ответа')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question')),
            ],
        ),
    ]
